import { nextJsConfig } from "@workspace/eslint-config/next-js";

export default [
  ...nextJsConfig,
  {
    // registry build artifacts (regenerated by `shadcn build`, not linted)
    ignores: ["out/**", "public/r/**"],
  },
];
